spring.application.name=SpringEcom
spring.datasource.url=jdbc:postgresql://localhost:5432/Shree
spring.datasource.username=postgres
spring.datasource.password=ShivShambhu
spring.jpa.hibernate.ddl-auto=update

